services:
  - type: web
    plan: free
    runtime: node
    name: n8n-service
    buildCommand: NODE_OPTIONS="--max-old-space-size=350" npm install --no-audit --no-fund
    startCommand: node --max-old-space-size=350 --gc-global --max-semi-space-size=2 ./node_modules/n8n/bin/n8n start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PORT
        value: 10000
      - key: N8N_PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=350
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
